import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Unused variable should be flagged
const unusedVariable = 42;

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    // Typo in JSX prop should be flagged by react/no-unknown-property
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`} // typo: should be className
        >
        {children}
        </body>
        </html>
    );
}

// Missing semicolon and console statement should also be flagged
console.log("Debuuug output")

const foo_bar = 1;