name: 🧹 Chore
description: Need to perform maintenance, update dependencies or track a routine task?
labels: ['Chore']
projects: ["SamHignett/1"]
assignees: ["SamHignett"]

body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please provide details about the routine task or maintenance required. Be as specific as possible to ensure clear understanding and efficient completion.
      
  - type: textarea
    id: steps_to_complete
    attributes:
      label: Steps to Complete
      description: Describe the chore, and list the steps required to complete the task.
      placeholder: Provide the steps required to complete the task
      value: |
        _N/A_
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or relevant information about the chore.
      placeholder: Include any additional context or relevant information
      value: |
        _N/A_
    validations:
      required: false