name: Build Node App

inputs:
  app-directory:
    description: "Directory of the Node app"
    required: true
  node-version:
    description: "Node.js version to use"
    required: true
    
runs:
  using: "composite"
  
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: npm install
      working-directory: ${{ inputs.app-directory }}
      shell: bash

    - name: Build
      run: npm run build
      working-directory: ${{ inputs.app-directory }}
      shell: bash