name: Build Portal

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
    build-portal:
        uses: ./.github/workflows/_build-react_app.yaml
        with:
            app-directory: src/frontend
            node-version: 20