name: Build Portal

on:
  pull_request:
    branches:
      - main

jobs:
    build-portal:
      name: Build Portal
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Build Portal
          uses: ./.github/actions/build-node-app
          with:
              app-directory: src/frontend
              node-version: 20
