name: Build ApiSuite

on:
  pull_request:
    branches:
      - main

jobs:
    build:
        name: Build ApiSuite
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Build API Suite
              uses: ./.github/actions/build-dotnet-app
              with:
                app-directory: 'src/backend'
                dotnet-version: '9.0.x'