name: Build Status (Main)

on:
  push:
    branches:
      - main
        
jobs:
    build-backend:
      uses: ./.github/workflows/build-backend.yaml
      
    build-portal:
        uses: ./.github/workflows/build-portal.yaml
        needs: build-backend