name: Test Backend

on:
  pull_request:
    branches:
      - main
      - uat
      - live

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run DotNet Tests on Backend
        uses: ./.github/actions/test-dotnet-app
        with:
          app-directory: 'src/backend'
          dotnet-version: '9.0.x'
      
      - name: Publish Test Results
        uses: dorny/test-reporter@v2
        if: ${{ always() }}
        with:
          name: 'Backend DotNet Tests'
          path: "src/backend/tests/**/TestResults/*.trx"
          reporter: 'dotnet-trx'